### ISSUE TITLE
ImportError: Twisted requires zope.interface 3.6.0 or later.

### ISSUE THREAD

**Issue by cryptid11** [blockstack/blockstack-server#208]
Just after installation with sudo pip install blockstack I get:
```
$ blockstack lookup fredwilson.id
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 34, in <module>
    from blockstore_client.blockstore_cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/__init__.py", line 24, in <module>
    import client
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/client.py", line 37, in <module>
    import parsing, schemas, storage, drivers, config, spv, utils
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/storage.py", line 43, in <module>
    from config import log
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/config.py", line 27, in <module>
    import virtualchain
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/__init__.py", line 28, in <module>
    from virtualchain import setup_virtualchain, run_virtualchain, stop_virtualchain, sync_virtualchain, stop_sync_virtualchain, virtualchain_set_opfields
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/virtualchain.py", line 38, in <module>
    from txjsonrpc.netstring import jsonrpc
  File "/usr/local/lib/python2.7/dist-packages/txjsonrpc/netstring/jsonrpc.py", line 10, in <module>
    from twisted.protocols import basic
  File "/usr/local/lib/python2.7/dist-packages/twisted/__init__.py", line 55, in <module>
    _checkRequirements()
  File "/usr/local/lib/python2.7/dist-packages/twisted/__init__.py", line 42, in _checkRequirements
    raise ImportError(required + ".")
ImportError: Twisted requires zope.interface 3.6.0 or later.

```

**Comment by cryptid11** [comment]
Twisted successfully installed and I also manage to install manually install zope from source here and all goes perfectly https://pypi.python.org/pypi/zope.interface/3.6.0 I read around can be for a version problem... I'm using Python 2.7.6

**Comment by muneeb-ali** [comment]
Thanks for reporting. This is documented [under troubleshooting](https://github.com/blockstack/blockstack-client/blob/master/README.md#troubleshooting-installation) with a possible solution, but I've noticed this issue come up a couple times so I'm going to leave this issue open and investigate it more.

**Comment by cryptid11** [comment]
I'm not in a virtual environment, I never use them.

**Comment by jcnelson** [comment]
We have since moved the `develop` branch off of Twisted.  This won't be a problem in the next release.

**Comment by jcnelson** [comment]
The problem is misleading--it's probably not an import error, but something completely unrelated.  See https://github.com/micahflee/torbrowser-launcher/issues/91 for details.  It does not look like the Twisted developers are keen on fixing this problem, so we will be migrating off of Twisted in the next release.

My recommendation is to try installing Twisted with your system package manager instead (i.e. `sudo apt-get install python-twisted` on Debian and Ubuntu).

**Comment by jcnelson** [comment]
The new stable release no longer relies on this package (or Twisted).
